(ns simplection.canvasgraph.csnormalization
  (:require [simplection.canvasgraph.definition :as definition]
            [simplection.canvasgraph.intersection :as intersection]
            [simplection.canvasgraph.scale :as scale]
            [simplection.canvasgraph.acoordinates :as acoordinates]
                                                                           )
  (      :require                        [simplection.core :as cr])
        (:import [simplection.canvasgraph.acoordinates Cartesian Polar]))

(def axes-grid
  (let [r ((cr/coordinates-resolver) (definition/get-type (definition/get-coordinate-system)))]
    (acoordinates/normalize-grid-coordinates
     r
     (acoordinates/generate-grid r scale/axes-points))))

(def series-coordinates
  (acoordinates/normalize-table-coordinates
   ((cr/coordinates-resolver) (definition/get-type (definition/get-coordinate-system)))
   intersection/series-coordinates))

;;;;;;;;;;;; This file autogenerated from src\cljx\simplection\canvasgraph\csnormalization.cljx
