(ns simplection.canvasgraph.csnormalization
  (:require [simplection.canvasgraph.definition :as definition]
            [simplection.canvasgraph.intersection :as intersection]
            [simplection.canvasgraph.acoordinates :as acoordinates]
                                                                           )
  (      :require                        [simplection.core :as cr])
        (:import [simplection.canvasgraph.acoordinates Cartesian Polar]))

(def series-coordinates
  (acoordinates/normalize-coordinates
   ((cr/coordinates-resolver) (definition/get-type (definition/get-coordinate-system)))
   intersection/series-coordinates))

;;;;;;;;;;;; This file autogenerated from src\cljx\simplection\canvasgraph\csnormalization.cljx
