(ns simplection.canvasgraph.csnormalization
  (:require [simplection.canvasgraph.definition :as definition]
            [simplection.canvasgraph.intersection :as intersection]
            [simplection.canvasgraph.acoordinates :as acoordinates]
            [simplection.canvasgraph.acoordinates :refer [Cartesian Polar]])
  (                      :require-macros [simplection.core :as cr])
                                                                        )

(def series-coordinates
  (acoordinates/normalize-coordinates
   ((cr/coordinates-resolver) (definition/get-type (definition/get-coordinate-system)))
   intersection/series-coordinates))

;;;;;;;;;;;; This file autogenerated from src\cljx\simplection\canvasgraph\csnormalization.cljx
